version: 2
updates:
- package-ecosystem: nuget
  directory: "/Chirp.CLI/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  - package-ecosystem: nuget
  directory: "/SimpleDB/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
