name: Build and Publish
run-name: ${{ github.actor }} is building and publishing

on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Build Linux
        shell: bash
        run: |
          tag=${{github.ref_name}}
          linux_release_name=Chirp-$tag-linux-x64

          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -f net7.0 -r linux-x64 --self-contained false -p:PublishSingleFile=true -p:DebugType=None -o "${linux_release_name}"

          7z a -tzip "${linux_release_name}.zip" "$linux_release_name"

          rm -r "$linux_release_name"

      - name: Build MacOS
        shell: bash
        run: |
          tag=${{github.ref_name}}
          osx_release_name=Chirp-$tag-osx-x64

          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -f net7.0 -r osx-x64 --self-contained false -p:PublishSingleFile=true -p:DebugType=None -o "${osx_release_name}"

          7z a -tzip "${osx_release_name}.zip" "$osx_release_name"

          rm -r "$osx_release_name"

      - name: Build MacOS Arm
        shell: bash
        run: |
          tag=${{github.ref_name}}
          macOS_arm_release_name=Chirp-$tag-osx-arm64
          
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -f net7.0 -r osx-arm64 --self-contained false -p:PublishSingleFile=true -p:DebugType=None -o "${macOS_arm_release_name}"

          7z a -tzip "${macOS_arm_release_name}.zip" "$macOS_arm_release_name"
          
          rm -r "$macOS_arm_release_name"

      - name: Build Windows
        shell: bash
        run: |
          tag=${{github.ref_name}}
          windows_release_name=Chirp-$tag-win-x64

          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -f net7.0 -r win-x64 --self-contained false -p:PublishSingleFile=true -p:DebugType=None -o "${windows_release_name}"

          7z a -tzip "${windows_release_name}.zip" "./${windows_release_name}/*"

          rm -r "$windows_release_name"
          
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Chirp-${{github.ref_name}}-linux-x64.zip
            Chirp-${{github.ref_name}}-osx-x64.zip
            Chirp-${{github.ref_name}}-osx-arm64.zip
            Chirp-${{github.ref_name}}-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
