name: Move assigned issues
run-name: Moving assigned issues

on:
  issues:
    types:
      - assigned
      
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ITU-BDSA23-GROUP19-Chirp
          column: In Progress
          repo-token: ${{ secrets.PROJECT_TOKEN }}