name: .NET Publish
run-name: ${{ github.actor }} is publishing.
on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build windows
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          windows_release_name=Chirp-$tag-win-x64

          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "${windows_release_name}"

          7z a -tzip "${windows_release_name}.zip" "./${windows_release_name}/*"

          rm -r "$windows_release_name"

      - name: Build linux
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          linux_release_name=Chirp-$tag-linux-x64

          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "${linux_release_name}"

          tar czvf "${linux_release_name}.tar.gz" "$linux_release_name"

          rm -r "$linux_release_name"

      - name: Build macOS
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          osx_release_name=Chirp-$tag-osx-x64

          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "${osx_release_name}"

          tar czvf "${osx_release_name}.tar.gz" "$osx_release_name"

          rm -r "$osx_release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
